// Code generated by speedfs-rpcgen. DO NOT EDIT.

package rpc

// EncodeTo
func (x *QuitCommand) EncodeTo(enc *Encoder) {
}

// DecodeFrom
func (x *QuitCommand) DecodeFrom(dec *Decoder) error {

	return nil
}

// Cmd
func (x *QuitCommand) Cmd() Cmd {
	return CmdQuit
}
