// Code generated by speedfs-gen. DO NOT EDIT.

package storage

import (
	"context"
	"syscall"

	"github.com/speedfs/speedfs/proto"
)

type method func(ctx context.Context, buf []byte) (proto.Message, error)

type handler struct {
	methods [256]method
	service *service
}

func NewHandler(service StorageService) proto.Handler {
	h := &handler{
		service: newService(service),
	}
	h.initMethods()
	return h
}

func (h *handler) Handle(ctx context.Context, cmd uint8, buf []byte) (proto.Message, error) {
	method := h.methods[cmd]
	if method == nil {
		return nil, syscall.EINVAL
	}
	return method(ctx, buf)
}

func (h *handler) initMethods() {
	h.methods[CmdUploadFile] = h.service.UploadFile
	h.methods[CmdUploadAppenderFile] = h.service.UploadAppenderFile
	h.methods[CmdSetMetadata] = h.service.SetMetadata
	h.methods[CmdGetMetadata] = h.service.GetMetadata
	h.methods[CmdDownloadFile] = h.service.DownloadFile
	h.methods[CmdAppendFile] = h.service.AppendFile
	h.methods[CmdModifyFile] = h.service.ModifyFile
	h.methods[CmdTruncateFile] = h.service.TruncateFile
	h.methods[CmdRenameFile] = h.service.RenameFile
}

type service struct {
	s StorageService
}

func newService(s StorageService) *service {
	return &service{
		s: s,
	}
}

func (s *service) UploadFile(ctx context.Context, buf []byte) (proto.Message, error) {
	cmd := new(UploadFileCommand)
	dec := proto.NewDecoder(buf)

	if err := cmd.DecodeFrom(dec); err != nil {
		return nil, err
	}

	return s.s.UploadFile(ctx, cmd)
}

func (s *service) UploadAppenderFile(ctx context.Context, buf []byte) (proto.Message, error) {
	cmd := new(UploadAppenderFileCommand)
	dec := proto.NewDecoder(buf)

	if err := cmd.DecodeFrom(dec); err != nil {
		return nil, err
	}

	return s.s.UploadAppenderFile(ctx, cmd)
}

func (s *service) SetMetadata(ctx context.Context, buf []byte) (proto.Message, error) {
	cmd := new(SetMetadataCommand)
	dec := proto.NewDecoder(buf)

	if err := cmd.DecodeFrom(dec); err != nil {
		return nil, err
	}

	return s.s.SetMetadata(ctx, cmd)
}

func (s *service) GetMetadata(ctx context.Context, buf []byte) (proto.Message, error) {
	cmd := new(GetMetadataCommand)
	dec := proto.NewDecoder(buf)

	if err := cmd.DecodeFrom(dec); err != nil {
		return nil, err
	}

	return s.s.GetMetadata(ctx, cmd)
}

func (s *service) DownloadFile(ctx context.Context, buf []byte) (proto.Message, error) {
	cmd := new(DownloadFileCommand)
	dec := proto.NewDecoder(buf)

	if err := cmd.DecodeFrom(dec); err != nil {
		return nil, err
	}

	return s.s.DownloadFile(ctx, cmd)
}

func (s *service) AppendFile(ctx context.Context, buf []byte) (proto.Message, error) {
	cmd := new(AppendFileCommand)
	dec := proto.NewDecoder(buf)

	if err := cmd.DecodeFrom(dec); err != nil {
		return nil, err
	}

	return s.s.AppendFile(ctx, cmd)
}

func (s *service) ModifyFile(ctx context.Context, buf []byte) (proto.Message, error) {
	cmd := new(ModifyFileCommand)
	dec := proto.NewDecoder(buf)

	if err := cmd.DecodeFrom(dec); err != nil {
		return nil, err
	}

	return s.s.ModifyFile(ctx, cmd)
}

func (s *service) TruncateFile(ctx context.Context, buf []byte) (proto.Message, error) {
	cmd := new(TruncateFileCommand)
	dec := proto.NewDecoder(buf)

	if err := cmd.DecodeFrom(dec); err != nil {
		return nil, err
	}

	return s.s.TruncateFile(ctx, cmd)
}

func (s *service) RenameFile(ctx context.Context, buf []byte) (proto.Message, error) {
	cmd := new(RenameFileCommand)
	dec := proto.NewDecoder(buf)

	if err := cmd.DecodeFrom(dec); err != nil {
		return nil, err
	}

	return s.s.RenameFile(ctx, cmd)
}
