// Code generated by speedfs-gen. DO NOT EDIT.

package proto

import (
	"github.com/speedfs/speedfs/internal/rpc"
)

func (x *QuitCommand) EncodeTo(enc *rpc.Encoder) {
}

func (x *Reply) EncodeTo(enc *rpc.Encoder) {
}

func (x *PingCommand) EncodeTo(enc *rpc.Encoder) {
}

func (x *PingReply) EncodeTo(enc *rpc.Encoder) {
}
