// Code generated by speedfs-gen. DO NOT EDIT.

package proto

import (
	"github.com/speedfs/speedfs/internal/rpc"
)

func (x *Header) EncodeTo(enc *rpc.Encoder) {
	enc.EncodeUint64(x.BodyLen)
	enc.EncodeUint8(x.Cmd)
	enc.EncodeInt8(x.Status)
}
