// Code generated by speedfs-rpcgen. DO NOT EDIT.

package tracker

import (
	"github.com/speedfs/speedfs/proto"
)

// EncodeTo
func (x *GroupStat) EncodeTo(enc *proto.Encoder) {
	enc.EncodeBytes(x.GroupName[:])
	enc.EncodeUint64(x.TotalMiB)
	enc.EncodeUint64(x.FreeMiB)
	enc.EncodeUint64(x.TrunkFreeMiB)
	enc.EncodeUint64(x.ServerCount)
	enc.EncodeUint64(x.StoragePort)
	enc.EncodeUint64(x.StorageHTTPPort)
	enc.EncodeUint64(x.ActiveServerCount)
	enc.EncodeUint64(x.CurrentWriteServer)
	enc.EncodeUint64(x.StorePathCount)
	enc.EncodeUint64(x.SubdirCountPerPath)
	enc.EncodeUint64(x.CurrentTrunkFileID)
}

// DecodeFrom
func (x *GroupStat) DecodeFrom(dec *proto.Decoder) error {

	var err error

	if err = dec.DecodeBytes(x.GroupName[:]); err != nil {
		return err
	}
	if x.TotalMiB, err = dec.DecodeUint64(); err != nil {
		return err
	}
	if x.FreeMiB, err = dec.DecodeUint64(); err != nil {
		return err
	}
	if x.TrunkFreeMiB, err = dec.DecodeUint64(); err != nil {
		return err
	}
	if x.ServerCount, err = dec.DecodeUint64(); err != nil {
		return err
	}
	if x.StoragePort, err = dec.DecodeUint64(); err != nil {
		return err
	}
	if x.StorageHTTPPort, err = dec.DecodeUint64(); err != nil {
		return err
	}
	if x.ActiveServerCount, err = dec.DecodeUint64(); err != nil {
		return err
	}
	if x.CurrentWriteServer, err = dec.DecodeUint64(); err != nil {
		return err
	}
	if x.StorePathCount, err = dec.DecodeUint64(); err != nil {
		return err
	}
	if x.SubdirCountPerPath, err = dec.DecodeUint64(); err != nil {
		return err
	}
	if x.CurrentTrunkFileID, err = dec.DecodeUint64(); err != nil {
		return err
	}

	return nil
}

// EncodeTo
func (x *GetGroupCommand) EncodeTo(enc *proto.Encoder) {
	enc.EncodeBytes(x.GroupName[:])
}

// DecodeFrom
func (x *GetGroupCommand) DecodeFrom(dec *proto.Decoder) error {

	var err error

	if err = dec.DecodeBytes(x.GroupName[:]); err != nil {
		return err
	}

	return nil
}

// Cmd
func (x *GetGroupCommand) Cmd() proto.Cmd {
	return CmdGetGroup
}

// EncodeTo
func (x *GetGroupReply) EncodeTo(enc *proto.Encoder) {
	x.GroupStat.EncodeTo(enc)
}

// DecodeFrom
func (x *GetGroupReply) DecodeFrom(dec *proto.Decoder) error {

	var err error

	if err = x.GroupStat.DecodeFrom(dec); err != nil {
		return err
	}

	return nil
}

// Cmd
func (x *GetGroupReply) Cmd() proto.Cmd {
	return CmdReply
}

// EncodeTo
func (x *ListGroupsCommand) EncodeTo(enc *proto.Encoder) {
}

// DecodeFrom
func (x *ListGroupsCommand) DecodeFrom(dec *proto.Decoder) error {

	return nil
}

// Cmd
func (x *ListGroupsCommand) Cmd() proto.Cmd {
	return CmdListGroups
}

// EncodeTo
func (x *ListGroupsReply) EncodeTo(enc *proto.Encoder) {
}

// DecodeFrom
func (x *ListGroupsReply) DecodeFrom(dec *proto.Decoder) error {

	return nil
}

// Cmd
func (x *ListGroupsReply) Cmd() proto.Cmd {
	return CmdReply
}

// EncodeTo
func (x *DeleteGroupCommand) EncodeTo(enc *proto.Encoder) {
	enc.EncodeBytes(x.GroupName[:])
}

// DecodeFrom
func (x *DeleteGroupCommand) DecodeFrom(dec *proto.Decoder) error {

	var err error

	if err = dec.DecodeBytes(x.GroupName[:]); err != nil {
		return err
	}

	return nil
}

// Cmd
func (x *DeleteGroupCommand) Cmd() proto.Cmd {
	return CmdDeleteGroup
}

// EncodeTo
func (x *DeleteGroupReply) EncodeTo(enc *proto.Encoder) {
}

// DecodeFrom
func (x *DeleteGroupReply) DecodeFrom(dec *proto.Decoder) error {

	return nil
}

// Cmd
func (x *DeleteGroupReply) Cmd() proto.Cmd {
	return CmdReply
}

// EncodeTo
func (x *ListGroupStoragesCommand) EncodeTo(enc *proto.Encoder) {
	enc.EncodeBytes(x.GroupName[:])
}

// DecodeFrom
func (x *ListGroupStoragesCommand) DecodeFrom(dec *proto.Decoder) error {

	var err error

	if err = dec.DecodeBytes(x.GroupName[:]); err != nil {
		return err
	}

	return nil
}

// Cmd
func (x *ListGroupStoragesCommand) Cmd() proto.Cmd {
	return CmdListGroupStorages
}

// EncodeTo
func (x *ListGroupStoragesReply) EncodeTo(enc *proto.Encoder) {
}

// DecodeFrom
func (x *ListGroupStoragesReply) DecodeFrom(dec *proto.Decoder) error {

	return nil
}

// Cmd
func (x *ListGroupStoragesReply) Cmd() proto.Cmd {
	return CmdReply
}

// EncodeTo
func (x *GetStorageCommand) EncodeTo(enc *proto.Encoder) {
	enc.EncodeBytes(x.GroupName[:])
	enc.EncodeBytes(x.StorageID[:])
}

// DecodeFrom
func (x *GetStorageCommand) DecodeFrom(dec *proto.Decoder) error {

	var err error

	if err = dec.DecodeBytes(x.GroupName[:]); err != nil {
		return err
	}
	if err = dec.DecodeBytes(x.StorageID[:]); err != nil {
		return err
	}

	return nil
}

// Cmd
func (x *GetStorageCommand) Cmd() proto.Cmd {
	return CmdGetStorage
}

// EncodeTo
func (x *GetStorageReply) EncodeTo(enc *proto.Encoder) {
}

// DecodeFrom
func (x *GetStorageReply) DecodeFrom(dec *proto.Decoder) error {

	return nil
}

// Cmd
func (x *GetStorageReply) Cmd() proto.Cmd {
	return CmdReply
}

// EncodeTo
func (x *DeleteStorageCommand) EncodeTo(enc *proto.Encoder) {
	enc.EncodeBytes(x.GroupName[:])
	enc.EncodeBytes(x.StorageID[:])
}

// DecodeFrom
func (x *DeleteStorageCommand) DecodeFrom(dec *proto.Decoder) error {

	var err error

	if err = dec.DecodeBytes(x.GroupName[:]); err != nil {
		return err
	}
	if err = dec.DecodeBytes(x.StorageID[:]); err != nil {
		return err
	}

	return nil
}

// Cmd
func (x *DeleteStorageCommand) Cmd() proto.Cmd {
	return CmdDeleteStorage
}

// EncodeTo
func (x *DeleteStorageReply) EncodeTo(enc *proto.Encoder) {
}

// DecodeFrom
func (x *DeleteStorageReply) DecodeFrom(dec *proto.Decoder) error {

	return nil
}

// Cmd
func (x *DeleteStorageReply) Cmd() proto.Cmd {
	return CmdReply
}

// EncodeTo
func (x *SetTrunkServerCommand) EncodeTo(enc *proto.Encoder) {
	enc.EncodeBytes(x.GroupName[:])
	enc.EncodeBytes(x.StorageID[:])
}

// DecodeFrom
func (x *SetTrunkServerCommand) DecodeFrom(dec *proto.Decoder) error {

	var err error

	if err = dec.DecodeBytes(x.GroupName[:]); err != nil {
		return err
	}
	if err = dec.DecodeBytes(x.StorageID[:]); err != nil {
		return err
	}

	return nil
}

// Cmd
func (x *SetTrunkServerCommand) Cmd() proto.Cmd {
	return CmdSetTrunkServer
}

// EncodeTo
func (x *SetTrunkServerReply) EncodeTo(enc *proto.Encoder) {
}

// DecodeFrom
func (x *SetTrunkServerReply) DecodeFrom(dec *proto.Decoder) error {

	return nil
}

// Cmd
func (x *SetTrunkServerReply) Cmd() proto.Cmd {
	return CmdReply
}

// EncodeTo
func (x *Addr) EncodeTo(enc *proto.Encoder) {
	enc.EncodeBytes(x.IP[:])
	enc.EncodeUint64(x.Port)
}

// DecodeFrom
func (x *Addr) DecodeFrom(dec *proto.Decoder) error {

	var err error

	if err = dec.DecodeBytes(x.IP[:]); err != nil {
		return err
	}
	if x.Port, err = dec.DecodeUint64(); err != nil {
		return err
	}

	return nil
}

// EncodeTo
func (x *QueryStorageCommand) EncodeTo(enc *proto.Encoder) {
}

// DecodeFrom
func (x *QueryStorageCommand) DecodeFrom(dec *proto.Decoder) error {

	return nil
}

// Cmd
func (x *QueryStorageCommand) Cmd() proto.Cmd {
	return CmdQueryStorage
}

// EncodeTo
func (x *QueryStorageReply) EncodeTo(enc *proto.Encoder) {
	enc.EncodeBytes(x.GroupName[:])
	x.Addr.EncodeTo(enc)
	enc.EncodeUint8(x.StorePathIndex)
}

// DecodeFrom
func (x *QueryStorageReply) DecodeFrom(dec *proto.Decoder) error {

	var err error

	if err = dec.DecodeBytes(x.GroupName[:]); err != nil {
		return err
	}
	if err = x.Addr.DecodeFrom(dec); err != nil {
		return err
	}
	if x.StorePathIndex, err = dec.DecodeUint8(); err != nil {
		return err
	}

	return nil
}

// Cmd
func (x *QueryStorageReply) Cmd() proto.Cmd {
	return CmdReply
}

// EncodeTo
func (x *QueryGroupStorageCommand) EncodeTo(enc *proto.Encoder) {
	enc.EncodeBytes(x.GroupName[:])
}

// DecodeFrom
func (x *QueryGroupStorageCommand) DecodeFrom(dec *proto.Decoder) error {

	var err error

	if err = dec.DecodeBytes(x.GroupName[:]); err != nil {
		return err
	}

	return nil
}

// Cmd
func (x *QueryGroupStorageCommand) Cmd() proto.Cmd {
	return CmdQueryGroupStorage
}

// EncodeTo
func (x *QueryGroupStorageReply) EncodeTo(enc *proto.Encoder) {
	enc.EncodeBytes(x.GroupName[:])
	x.Addr.EncodeTo(enc)
	enc.EncodeUint8(x.StorePathIndex)
}

// DecodeFrom
func (x *QueryGroupStorageReply) DecodeFrom(dec *proto.Decoder) error {

	var err error

	if err = dec.DecodeBytes(x.GroupName[:]); err != nil {
		return err
	}
	if err = x.Addr.DecodeFrom(dec); err != nil {
		return err
	}
	if x.StorePathIndex, err = dec.DecodeUint8(); err != nil {
		return err
	}

	return nil
}

// Cmd
func (x *QueryGroupStorageReply) Cmd() proto.Cmd {
	return CmdReply
}

// EncodeTo
func (x *QueryStoragesCommand) EncodeTo(enc *proto.Encoder) {
}

// DecodeFrom
func (x *QueryStoragesCommand) DecodeFrom(dec *proto.Decoder) error {

	return nil
}

// Cmd
func (x *QueryStoragesCommand) Cmd() proto.Cmd {
	return CmdQueryStorages
}

// EncodeTo
func (x *QueryStoragesReply) EncodeTo(enc *proto.Encoder) {
	enc.EncodeBytes(x.GroupName[:])
	enc.EncodeUint8(x.StorePathIndex)
}

// DecodeFrom
func (x *QueryStoragesReply) DecodeFrom(dec *proto.Decoder) error {

	var err error

	if err = dec.DecodeBytes(x.GroupName[:]); err != nil {
		return err
	}
	if x.StorePathIndex, err = dec.DecodeUint8(); err != nil {
		return err
	}

	return nil
}

// Cmd
func (x *QueryStoragesReply) Cmd() proto.Cmd {
	return CmdReply
}

// EncodeTo
func (x *QueryGroupStoragesCommand) EncodeTo(enc *proto.Encoder) {
	enc.EncodeBytes(x.GroupName[:])
}

// DecodeFrom
func (x *QueryGroupStoragesCommand) DecodeFrom(dec *proto.Decoder) error {

	var err error

	if err = dec.DecodeBytes(x.GroupName[:]); err != nil {
		return err
	}

	return nil
}

// Cmd
func (x *QueryGroupStoragesCommand) Cmd() proto.Cmd {
	return CmdQueryGroupStorages
}

// EncodeTo
func (x *QueryGroupStoragesReply) EncodeTo(enc *proto.Encoder) {
	enc.EncodeBytes(x.GroupName[:])
	enc.EncodeUint8(x.StorePathIndex)
}

// DecodeFrom
func (x *QueryGroupStoragesReply) DecodeFrom(dec *proto.Decoder) error {

	var err error

	if err = dec.DecodeBytes(x.GroupName[:]); err != nil {
		return err
	}
	if x.StorePathIndex, err = dec.DecodeUint8(); err != nil {
		return err
	}

	return nil
}

// Cmd
func (x *QueryGroupStoragesReply) Cmd() proto.Cmd {
	return CmdReply
}

// EncodeTo
func (x *QueryDownloadableStorageCommand) EncodeTo(enc *proto.Encoder) {
	enc.EncodeBytes(x.GroupName[:])
	enc.EncodeString(x.Filename)
}

// DecodeFrom
func (x *QueryDownloadableStorageCommand) DecodeFrom(dec *proto.Decoder) error {

	var err error

	if err = dec.DecodeBytes(x.GroupName[:]); err != nil {
		return err
	}
	x.Filename = string(dec.Bytes())

	return nil
}

// Cmd
func (x *QueryDownloadableStorageCommand) Cmd() proto.Cmd {
	return CmdQueryDownloadableStorage
}

// EncodeTo
func (x *QueryDownloadableStorageReply) EncodeTo(enc *proto.Encoder) {
	enc.EncodeBytes(x.GroupName[:])
	x.Addr.EncodeTo(enc)
}

// DecodeFrom
func (x *QueryDownloadableStorageReply) DecodeFrom(dec *proto.Decoder) error {

	var err error

	if err = dec.DecodeBytes(x.GroupName[:]); err != nil {
		return err
	}
	if err = x.Addr.DecodeFrom(dec); err != nil {
		return err
	}

	return nil
}

// Cmd
func (x *QueryDownloadableStorageReply) Cmd() proto.Cmd {
	return CmdReply
}

// EncodeTo
func (x *QueryDownloadableStoragesCommand) EncodeTo(enc *proto.Encoder) {
	enc.EncodeBytes(x.GroupName[:])
	enc.EncodeString(x.Filename)
}

// DecodeFrom
func (x *QueryDownloadableStoragesCommand) DecodeFrom(dec *proto.Decoder) error {

	var err error

	if err = dec.DecodeBytes(x.GroupName[:]); err != nil {
		return err
	}
	x.Filename = string(dec.Bytes())

	return nil
}

// Cmd
func (x *QueryDownloadableStoragesCommand) Cmd() proto.Cmd {
	return CmdQueryDownloadableStorages
}

// EncodeTo
func (x *QueryDownloadableStoragesReply) EncodeTo(enc *proto.Encoder) {
	enc.EncodeBytes(x.GroupName[:])
	enc.EncodeUint8(x.Port)
}

// DecodeFrom
func (x *QueryDownloadableStoragesReply) DecodeFrom(dec *proto.Decoder) error {

	var err error

	if err = dec.DecodeBytes(x.GroupName[:]); err != nil {
		return err
	}
	if x.Port, err = dec.DecodeUint8(); err != nil {
		return err
	}

	return nil
}

// Cmd
func (x *QueryDownloadableStoragesReply) Cmd() proto.Cmd {
	return CmdReply
}

// EncodeTo
func (x *QueryUpdatableStorageCommand) EncodeTo(enc *proto.Encoder) {
	enc.EncodeBytes(x.GroupName[:])
	enc.EncodeString(x.Filename)
}

// DecodeFrom
func (x *QueryUpdatableStorageCommand) DecodeFrom(dec *proto.Decoder) error {

	var err error

	if err = dec.DecodeBytes(x.GroupName[:]); err != nil {
		return err
	}
	x.Filename = string(dec.Bytes())

	return nil
}

// Cmd
func (x *QueryUpdatableStorageCommand) Cmd() proto.Cmd {
	return CmdQueryUpdatableStorage
}

// EncodeTo
func (x *QueryUpdatableStorageReply) EncodeTo(enc *proto.Encoder) {
	enc.EncodeBytes(x.GroupName[:])
	x.Addr.EncodeTo(enc)
}

// DecodeFrom
func (x *QueryUpdatableStorageReply) DecodeFrom(dec *proto.Decoder) error {

	var err error

	if err = dec.DecodeBytes(x.GroupName[:]); err != nil {
		return err
	}
	if err = x.Addr.DecodeFrom(dec); err != nil {
		return err
	}

	return nil
}

// Cmd
func (x *QueryUpdatableStorageReply) Cmd() proto.Cmd {
	return CmdReply
}
