// Code generated by speedfs-gen. DO NOT EDIT.

package tracker

import (
	"context"
	"syscall"

	"github.com/speedfs/speedfs/proto"
)

type method func(ctx context.Context, buf []byte) (proto.Message, error)

type handler struct {
	methods [256]method
	service *service
}

func NewHandler(service TrackerService) proto.Handler {
	h := &handler{
		service: newService(service),
	}
	h.initMethods()
	return h
}

func (h *handler) Handle(ctx context.Context, cmd uint8, buf []byte) (proto.Message, error) {
	method := h.methods[cmd]
	if method == nil {
		return nil, syscall.EINVAL
	}
	return method(ctx, buf)
}

func (h *handler) initMethods() {
	h.methods[CmdQueryStorage] = h.service.QueryStorage
}

type service struct {
	s TrackerService
}

func newService(s TrackerService) *service {
	return &service{
		s: s,
	}
}

func (s *service) QueryStorage(ctx context.Context, buf []byte) (proto.Message, error) {
	cmd := new(QueryStorageCommand)
	dec := proto.NewDecoder(buf)

	if err := cmd.DecodeFrom(dec); err != nil {
		return nil, err
	}

	return s.s.QueryStorage(ctx, cmd)
}
